spring:
  profiles:
    default: dev
  application:
    name: DeviceIntegrationApi

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

integration:
  ventilator:
    terminal:
      start_script: "/mnt/ventilator/run.sh --input /mnt/ventilator/examples/ventilator-onoff.json"
      stop_script: "/mnt/ventilator/run.sh --input /mnt/ventilator/examples/ventilator-onoff.json"
      speed_script: "/mnt/ventilator/run.sh --input /mnt/ventilator/examples/ventilator-speed.json"

