spring:
  profiles:
    default: dev
  application:
    name: DeviceIntegrationApi

management:
  endpoints:
    web:
      exposure:
        include: health

integration:
  ventilator:
    terminal:
      start_script: ${VENTILATOR_BASH_START}
      stop_script: ${VENTILATOR_BASH_STOP}
      speed_script: ${VENTILATOR_BASH_SPEED}

#/mnt/ventilator/run.sh --input /mnt/ventilator/examples/ventilator-onoff.json"
