spring:
  profiles:
    default: dev
  application:
    name: DeviceIntegrationApi

management:
  endpoints:
    web:
      exposure:
        include: health

integration:
  ventilator:
    terminal:
      dir: ${VENTILATOR_SCRIPT_DIR:-}
      start_script: ${VENTILATOR_BASH_START:-}
      stop_script: ${VENTILATOR_BASH_STOP:-}
      speed_script: ${VENTILATOR_BASH_SPEED:-}
      rotate_script: ${VENTILATOR_BASH_ROTATE:-}
