### Start Ventilator
POST {{host}}/api/ventilator/start
Accept: application/json

### Stop Ventilator
POST {{host}}/api/ventilator/stop
Accept: application/json

### Set Ventilator Speed
PUT {{host}}/api/ventilator/speed/3
Accept: application/json

###
POST {{host}}/api/ventilator/rotate
Accept: application/json

###
GET {{host}}/api/ventilator/state
Accept: application/json

### Healthcheck
GET {{host}}/actuator/health
Accept: application/json